//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ile_pas
    {
        public long Id { get; set; }
        public long Id_lot { get; set; }
        public long Ile_pas1 { get; set; }
        public Nullable<long> typ { get; set; }
        public Nullable<long> pas_wol { get; set; }
    }
}
