//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogRegEntities : DbContext
    {
        public LogRegEntities()
            : base("name=LogRegEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ile_pas> Ile_pas { get; set; }
        public virtual DbSet<LogReg> LogRegs { get; set; }
        public virtual DbSet<lotnisko> lotniskoes { get; set; }
        public virtual DbSet<przewoznik> przewozniks { get; set; }
        public virtual DbSet<zar_uzyt> zar_uzyt { get; set; }
    }
}
