//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class przewoznik
    {
        public long Id { get; set; }
        public long K_kl_pierwszej { get; set; }
        public long K_kl_biznesowej { get; set; }
        public long K_kl_ekonomicznej { get; set; }
        public long K_bag_do25 { get; set; }
        public long I_miejsc { get; set; }
        public string Cz_trwania { get; set; }
        public string Przesiadki { get; set; }
        public Nullable<long> Id_prze { get; set; }
        public string Z { get; set; }
        public string DO { get; set; }
        public long K_bag_pow25 { get; set; }
        public string Nr_lot { get; set; }
    }
}
